[package]
name = "telchar-codegen"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/txpipe/telchar"

[dependencies]
handlebars = "6.0.0"
heck = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
